export const judoQuestions = [
    { question: 'Deashi Harai (or barai) ', answer: 'Advanced Foot Sweep' },
    { question: 'Hiza Guruma ', answer: 'Knee Wheel' },
    { question: 'Sasae Tsurikomi Ashi ', answer: 'Supporting Lift-Pull Foot' },
    { question: 'Uki Goshi ', answer: 'Floating Hip' },
    { question: 'Osoto Gari ', answer: 'Major Outer Reap' },
    { question: 'O Goshi ', answer: 'Major Hip' },
    { question: 'Ouchi Gari ', answer: 'Major Inner Reap' },
    { question: 'Seoi Nage ', answer: 'Shoulder Throw' },
    { question: 'Kosoto Gari ', answer: 'Minor Outer Reap' },
    { question: 'Kouchi Gari ', answer: 'Minor Inner Reap' },
    { question: 'Koshi Guruma', answer: 'Hip Wheel' },
    { question: 'Tsurikomi Goshi ', answer: 'Lift-Pull Hip' },
    { question: 'Okuriashi Harai ', answer: 'Assisting Foot Sweep' },
    { question: 'Tai Otoshi ', answer: 'Body Drop' },
    { question: 'Harai Goshi ', answer: 'Sweeping Hip' },
    { question: 'Uchi Mata ', answer: 'Inner Thigh' },
    { question: 'Kosoto Gake ', answer: 'Minor Outer Hook' },
    { question: 'Tsuri Goshi ', answer: 'Lifting Hip' },
    { question: 'Yoko Otoshi ', answer: 'Side Drop' },
    { question: 'Ashi Guruma ', answer: 'Foot Wheel' },
    { question: 'Hane Goshi ', answer: 'Springing Hip' },
    { question: 'Harai Tsurikomi Ashi ', answer: 'Sweeping Lift-Pull Foot' },
    { question: 'Tomoe Nage ', answer: 'Stomach Throw' },
    { question: 'Kata Guruma ', answer: 'Shoulder Wheel' },
    { question: 'Sumi Gaeshi ', answer: 'Corner Reversal' },
    { question: 'Tani Otoshi ', answer: 'Valley Drop' },
    { question: 'Hane Makikomi ', answer: 'Springing Body Wrap' },
    { question: 'Sukui Nage ', answer: 'Scooping Throw' },
    { question: 'Utsuri Goshi ', answer: 'Transfer Hip' },
    { question: 'O Guruma ', answer: 'Major Wheel' },
    { question: 'Soto Makikomi ', answer: 'Outside Body Wrap' },
    { question: 'Uki Otoshi ', answer: 'Floating Drop' },
    { question: 'Osoto Guruma ', answer: 'Major Outer Wheel' },
    { question: 'Uki Waza ', answer: 'Floating Technique' },
    { question: 'Yoko Wakare ', answer: 'Side Separation' },
    { question: 'Yoko Guruma ', answer: 'Side Wheel' },
    { question: 'Ushiro Goshi ', answer: 'Rear Hip' },
    { question: 'Ura Nage ', answer: 'Back Throw' },
    { question: 'Sumi Otoshi ', answer: 'Corner Drop' },
    { question: 'Yoko Gake ', answer: 'Side Hook' },
]